apiVersion: v1
kind: Pod
metadata:
  name: indexhtml
  namespace: tomcat-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: tomcat
    volumeMounts:
    - name: indexhtml
      mountPath: /var/www/html/index.html
      subPath: index.html
  volumes:
  - name: indexhtml
    configMap:
     name: tomcat-apache
