apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    app: tomcat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:7.0.90
        
